#Versión ligera de Node LTS.
FROM node:22.15.0-alpine
WORKDIR /Frontend/front-service
COPY package.json package-lock.json ./
RUN npm install
COPY . .
RUN npm run build
EXPOSE 4000
CMD ["npm", "run","start"]

