#Se utiliza una versión ligera de python.
FROM python:3.11-alpine

#Instalo dependencias con el gestor de paquetería de alpine.
    #--no-cache: no se guardarán archivos temporales.
    #gcc: Compilador de C(para utilizar numpy)
    #musl-dev:  dependencia de numpy
RUN apk add --no-cache gcc musl-dev

#Actualizo versión de gestor de paquetes de python.
RUN py -m pip install --upgrade pip 

#Accedo a la carpeta donde se ejecutará el código
WORKDIR /app

#Copio los archivos a la imágen.
COPY . .

#Instalo paqueterías necesarias desde el archivo requirements.txt (se omiten archivos temporales)
RUN pip install --no-cache-dir -r requirements.txt

#Expongo el puerto a utilizar (buena práctica)
EXPOSE 8000

#Inicio servicio con uvicorn.
CMD ["uvicorn", "app:server", "--host", "0.0.0.0", "--port", "8000", "--reload"]
